DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS films CASCADE;

DROP TABLE IF EXISTS likes CASCADE;

DROP TABLE IF EXISTS friends CASCADE;

DROP TABLE IF EXISTS film_genres CASCADE;

DROP TABLE IF EXISTS genre CASCADE;

DROP TABLE IF EXISTS mpa CASCADE;

CREATE TABLE mpa (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(10)
);

CREATE TABLE genre (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(20)
);

CREATE TABLE users (
	user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(50) NOT NULL,
	login varchar(50) NOT NULL,
	username varchar(50),
	birthday date NOT NULL
);

CREATE TABLE films (
	film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_name varchar(40) NOT NULL,
	description varchar,
	release_date date NOT NULL,
	duration int NOT NULL,
	mpa int REFERENCES mpa(id),
	rate int
);

CREATE TABLE likes (
	user_id bigint REFERENCES users(user_id),
	film_id bigint REFERENCES films(film_id),
	primary key(user_id, film_id)
);

CREATE TABLE friends (
	user_id bigint REFERENCES users(user_id),
	friend_id bigint REFERENCES users(user_id),
	status boolean DEFAULT false,
	primary key(user_id, friend_id)
);

CREATE TABLE film_genres (
	film_id bigint REFERENCES films(film_id),
	id int REFERENCES genre(id)
);

