DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS films CASCADE;

DROP TABLE IF EXISTS likes CASCADE;

DROP TABLE IF EXISTS friends CASCADE;

DROP TABLE IF EXISTS film_genries CASCADE;

DROP TABLE IF EXISTS genre CASCADE;

DROP TABLE IF EXISTS rating CASCADE;

CREATE TABLE rating (
	rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rating_name varchar(10)
);

CREATE TABLE genre (
	genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre_name varchar(20)
);

CREATE TABLE users (
	user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(50) NOT NULL,
	login varchar(50) NOT NULL,
	username varchar(50),
	birthday date NOT NULL
);

CREATE TABLE films (
	film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_name varchar(40) NOT NULL,
	description varchar,
	release_date date NOT NULL,
	duration int NOT NULL,
	rating_id int REFERENCES rating(rating_id)
);

CREATE TABLE likes (
	user_id bigint REFERENCES users(user_id),
	film_id bigint REFERENCES films(film_id)
);

CREATE TABLE friends (
	user_id bigint REFERENCES users(user_id),
	friend_id bigint REFERENCES users(user_id),
	status boolean DEFAULT false
);

CREATE TABLE film_genres (
	film_id bigint REFERENCES films(film_id),
	genre_id int REFERENCES genre(genre_id)
);

